# Generated by Django 4.2.6 on 2023-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='duracion',
            field=models.CharField(choices=[('30', '30 minutos'), ('60', '1 hora'), ('90', '1 hora y 30 minutos')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
