# Generated by Django 4.2.6 on 2023-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_clases_duracion_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='apertura',
            field=models.CharField(choices=[('6:30', '6:30'), ('7am', '7:00'), ('7:30', '7:30'), ('8am', '8:00')], max_length=5),
        ),
    ]
