# Generated by Django 4.2.6 on 2023-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado')], default='Lunes', max_length=15),
        ),
    ]
