# Generated by Django 4.2.6 on 2023-10-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_alter_clases_hora_inicio_alter_clases_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='periodo',
        ),
    ]
